// SPDX-License-Identifier: AGPL-3.0-or-later

namespace CourseMoth.Core.Domain;

public enum TaskSourceType
{
    Automatic,
    User,
}

public enum TaskGoalType
{
    /// <summary>Watch N lessons.</summary>
    WatchLessons,

    /// <summary>Watch N minutes.</summary>
    WatchMinutes,

    /// <summary>Finish a module.</summary>
    CompleteModule,

    /// <summary>Finish a course.</summary>
    CompleteCourse,

    /// <summary>Reach X% of a course.</summary>
    ReachPercent,
}

/// <summary>
/// Recurrence rule. Recurring tasks produce one instance per occurrence, not a counter —
/// a counter cannot answer "did I complete Tuesday's task". See TasksStreaksSpec §7.
/// </summary>
public record RecurrenceRule(DayOfWeek[] Days, DateTime? Until);

/// <summary>
/// A learning goal, either generated by the app or created by the user.
/// Target and completed values are kept separately so progress can be shown
/// ("1 of 2 lessons") rather than only a tick. See DomainMap §5.1.
/// </summary>
public class LearningTask
{
    public Guid Id { get; set; }
    public string Title { get; set; } = string.Empty;

    /// <summary>Null for a library-wide task.</summary>
    public Guid? CourseId { get; set; }

    /// <summary>Null unless the task is scoped to a single module.</summary>
    public Guid? ModuleId { get; set; }

    public TaskSourceType Source { get; set; }
    public TaskGoalType GoalType { get; set; }

    public double TargetValue { get; set; }
    public double CompletedValue { get; set; }

    public DateTime? DueDate { get; set; }
    public RecurrenceRule? Recurrence { get; set; }

    public bool IsCompleted { get; set; }
    public DateTime? CompletedAt { get; set; }

    public DateTime CreatedAt { get; set; }
    public DateTime UpdatedAt { get; set; }
}
