// SPDX-License-Identifier: AGPL-3.0-or-later

using CourseMoth.Core.Abstractions;
using CourseMoth.Core.Domain;

namespace CourseMoth.Core.Tests.Fakes;

/// <summary>
/// Hand-written in-memory repositories. Deliberately hand-written rather than generated by a
/// mocking framework: a fake that stores what it is given also proves the service writes what
/// it claims to write, which a recorded interaction does not.
///
/// Every fake keeps its rows in insertion order so assertions can talk about "the second task
/// of the day" without depending on an unspecified ordering.
/// </summary>
public sealed class InMemoryRepositories
{
    public InMemoryCourseRepository Courses { get; } = new();
    public InMemoryCourseModuleRepository Modules { get; } = new();
    public InMemoryLessonRepository Lessons { get; } = new();
    public InMemoryWatchStateRepository WatchStates { get; } = new();
    public InMemoryTaskRepository Tasks { get; } = new();
    public InMemoryActivityRepository Activities { get; } = new();
    public InMemoryCategoryRepository Categories { get; } = new();
    public InMemoryLibrarySourceRepository Sources { get; } = new();
    public CountingUnitOfWork UnitOfWork { get; } = new();
}

public sealed class InMemoryCourseRepository : ICourseRepository
{
    private readonly List<Course> _courses = [];
    private readonly Dictionary<Guid, Course> _byId = [];

    public Task<Course?> GetAsync(Guid id, CancellationToken ct = default)
        => Task.FromResult(_byId.GetValueOrDefault(id));

    public Task<Course?> GetByStableKeyAsync(string stableKey, CancellationToken ct = default)
        => Task.FromResult(_courses.FirstOrDefault(c => c.StableKey == stableKey));

    public Task<IReadOnlyList<Course>> ListAsync(CancellationToken ct = default)
        => Task.FromResult<IReadOnlyList<Course>>(_courses.ToList());

    public Task AddAsync(Course course, CancellationToken ct = default)
    {
        _courses.Add(course);
        _byId[course.Id] = course;
        return Task.CompletedTask;
    }

    public Task UpdateAsync(Course course, CancellationToken ct = default)
    {
        _byId[course.Id] = course;
        var index = _courses.FindIndex(c => c.Id == course.Id);
        if (index >= 0)
        {
            _courses[index] = course;
        }

        return Task.CompletedTask;
    }

    /// <summary>Test helper: seed a course that is already stored.</summary>
    public void Seed(Course course)
    {
        _courses.Add(course);
        _byId[course.Id] = course;
    }
}

public sealed class InMemoryCourseModuleRepository : ICourseModuleRepository
{
    private readonly List<CourseModule> _modules = [];

    public Task<IReadOnlyList<CourseModule>> ListByCourseAsync(Guid courseId, CancellationToken ct = default)
        => Task.FromResult<IReadOnlyList<CourseModule>>(
            _modules.Where(m => m.CourseId == courseId).OrderBy(m => m.Order).ToList());

    public Task AddRangeAsync(IEnumerable<CourseModule> modules, CancellationToken ct = default)
    {
        _modules.AddRange(modules);
        return Task.CompletedTask;
    }

    public IReadOnlyList<CourseModule> All => _modules;
}

public sealed class InMemoryLessonRepository : ILessonRepository
{
    private readonly List<Lesson> _lessons = [];
    private readonly Dictionary<Guid, Lesson> _byId = [];

    public Task<Lesson?> GetAsync(Guid id, CancellationToken ct = default)
        => Task.FromResult(_byId.GetValueOrDefault(id));

    public Task<IReadOnlyList<Lesson>> ListByCourseAsync(Guid courseId, CancellationToken ct = default)
        => Task.FromResult<IReadOnlyList<Lesson>>(
            _lessons.Where(l => l.CourseId == courseId).OrderBy(l => l.Order).ToList());

    public Task AddRangeAsync(IEnumerable<Lesson> lessons, CancellationToken ct = default)
    {
        foreach (var lesson in lessons)
        {
            _lessons.Add(lesson);
            _byId[lesson.Id] = lesson;
        }

        return Task.CompletedTask;
    }

    public Task UpdateAsync(Lesson lesson, CancellationToken ct = default)
    {
        _byId[lesson.Id] = lesson;
        return Task.CompletedTask;
    }

    public IReadOnlyList<Lesson> All => _lessons;

    public void Seed(Lesson lesson)
    {
        _lessons.Add(lesson);
        _byId[lesson.Id] = lesson;
    }
}

public sealed class InMemoryWatchStateRepository : IWatchStateRepository
{
    private readonly Dictionary<Guid, WatchState> _byLesson = [];

    public Task<WatchState?> GetAsync(Guid lessonId, CancellationToken ct = default)
        => Task.FromResult(_byLesson.GetValueOrDefault(lessonId));

    public Task<IReadOnlyDictionary<Guid, WatchState>> GetForLessonsAsync(
        IReadOnlyCollection<Guid> lessonIds, CancellationToken ct = default)
    {
        var result = lessonIds
            .Where(_byLesson.ContainsKey)
            .ToDictionary(id => id, id => _byLesson[id]);

        return Task.FromResult<IReadOnlyDictionary<Guid, WatchState>>(result);
    }

    public Task SaveAsync(WatchState state, CancellationToken ct = default)
    {
        _byLesson[state.LessonId] = state;
        return Task.CompletedTask;
    }

    /// <summary>Test helper: seed a state without going through the service under test.</summary>
    public void Seed(WatchState state) => _byLesson[state.LessonId] = state;
}

public sealed class InMemoryTaskRepository : ITaskRepository
{
    private readonly List<LearningTask> _tasks = [];
    private readonly Dictionary<Guid, LearningTask> _byId = [];

    /// <summary>
    /// The tasks on <paramref name="date"/>. This copies the semantics of the real
    /// <c>TaskRepository.ListForDateAsync</c> in <c>CourseMoth.Data</c>. The two are only useful
    /// while they agree: a fake that answers a different question from production is worse than
    /// no fake.
    ///
    /// <para>
    /// <b>The window is the calendar day</b> <c>[date 00:00, date + 1 00:00)</c>, <b>plus the
    /// boundary instant that closes the study day</b>. The calendar day is the scale this
    /// repository stores on: <c>DueDate</c> is written as a <c>yyyyMMdd</c> date key by
    /// <c>SqliteValueConverters.ToDateKey</c>, and the <c>TaskEvaluator</c> seeds and reads its
    /// rows on the same day. <c>TaskEvaluator.DueDateFor</c> then stamps a study day's generated
    /// tasks at the boundary that <i>closes</i> it — 04:00 on the following calendar day
    /// (TasksStreaksSpec §3: "a study day ends when the next one begins") — and that instant needs
    /// an arm of its own or the tasks the evaluator has just written match no day at all.
    /// </para>
    ///
    /// <para>
    /// <b>The boundary arm is deliberately restricted to the closing instant of this day.</b> A
    /// stamp belongs to the day it closes, not the day it opens, so it is reachable from
    /// <c>date</c> and not from <c>date + 1</c>. Widening it — or stretching the window's own
    /// edges out to the boundary — makes day 1's tasks visible on day 2, at which point
    /// <c>GenerateAutomaticTasksAsync</c> sees a non-empty set, concludes the day has already been
    /// generated, and never produces one for the new day. That is the failure
    /// <c>TaskEvaluatorTests.A_second_day_gets_its_own_set_of_tasks</c> exists to catch.
    /// </para>
    ///
    /// <para>
    /// <b>The boundary is not a parameter of this repository, and cannot be.</b> Production stores
    /// only the <c>DueDate</c>; the boundary is a user setting the query never receives. The window
    /// below therefore uses the default boundary, which is the one the suite configures.
    /// </para>
    ///
    /// <para>
    /// <b>An undated task belongs to every day.</b> Production matches
    /// <c>DueDateKey == null ||</c> … first: an undated task is one the user has not scheduled, and
    /// hiding it from every day would hide it permanently.
    /// </para>
    ///
    /// <para>
    /// A task with a recurrence rule also matches every day inside its window. The rule is not
    /// interpreted here — nothing in the suite seeds one, and a half-correct reading of
    /// <c>RecurrenceDays</c> would be a third source of truth. Seed the instances, not the rule.
    /// </para>
    ///
    /// <para>
    /// The order is production's order: incomplete before complete, then by title. It is
    /// load-bearing rather than cosmetic. <c>TaskEvaluator.EvaluateAsync</c> returns the list
    /// untouched the moment nothing needed recomputing, so a repository that always reported
    /// changes would defeat that short circuit.
    /// </para>
    /// </summary>
    public Task<IReadOnlyList<LearningTask>> ListForDateAsync(DateOnly date, CancellationToken ct = default)
        => Task.FromResult<IReadOnlyList<LearningTask>>(ListForDate(date));

    /// <summary>
    /// The window itself, exposed so the harness can assert on it directly. See
    /// <see cref="ListForDateAsync"/> for why it is shaped this way.
    /// </summary>
    internal IReadOnlyList<LearningTask> ListForDate(DateOnly date)
    {
        var dayStart = date.ToDateTime(TimeOnly.MinValue, DateTimeKind.Unspecified);
        var dayEnd = dayStart.AddDays(1);
        var closingBoundary = dayEnd + new DayBoundaryOptions().DayBoundary;

        var forDate = _tasks
            .Where(t => t.DueDate is not { } due || InWindow(due, dayStart, dayEnd, closingBoundary))
            .OrderBy(t => t.IsCompleted)
            .ThenBy(t => t.Title, StringComparer.Ordinal)
            .ToList();

        return forDate;
    }

    /// <summary>
    /// The calendar day, plus this day's own closing boundary.
    ///
    /// <para>
    /// The comparisons are on <c>Ticks</c> and must stay that way. <c>DateTime.==</c> compares
    /// <c>InternalTicks</c>, which folds in a kind-dependent flag, so a <c>Local</c> and an
    /// <c>Unspecified</c> value with identical ticks are <b>not</b> equal under <c>==</c>. The
    /// clock's stamp is <c>Local</c> (<c>DueDateFor</c> uses <c>DateTime.SpecifyKind</c>) while
    /// these edges are <c>Unspecified</c>, so a <c>due == closingBoundary</c> arm would silently
    /// never fire and reject the very stamp it exists to recognise.
    /// </para>
    /// </summary>
    private static bool InWindow(DateTime due, DateTime dayStart, DateTime dayEnd, DateTime closingBoundary)
    {
        if (due.Ticks >= dayStart.Ticks && due.Ticks < dayEnd.Ticks)
        {
            return true;
        }

        return due.Kind == DateTimeKind.Local && due.Ticks == closingBoundary.Ticks;
    }

    /// <summary>
    /// Whether an instant landing exactly on the closing boundary is the clock's stamp rather than
    /// a genuine midnight due date.
    ///
    /// <para>
    /// The database can tell these apart and this fake cannot, because the boundary is a setting
    /// and not a column: <c>DateTime.Date</c> of 11 March 04:00 is the 11th, so production keys a
    /// generated task to the day it <i>closes</i>, while a task the user scheduled for midnight on
    /// the 11th is keyed to the 11th as the day it <i>opens</i>. Both arrive here as
    /// <c>2026-03-11T00:00</c> on a 04:00 boundary.
    /// </para>
    ///
    /// <para>
    /// The suite seeds no task due at midnight, so the ambiguity never bites. The kind is what
    /// separates them: <c>TaskEvaluator.DueDateFor</c> builds its stamp through
    /// <c>DateTime.SpecifyKind(…, DateTimeKind.Local)</c>, while a task constructed from a
    /// <c>DateOnly</c> the way the tests do is <c>Unspecified</c>.
    /// </para>
    /// </summary>
    private static bool IsBoundaryStamp(DateTime due) => due.Kind == DateTimeKind.Local;

    public Task<LearningTask?> GetAsync(Guid id, CancellationToken ct = default)
        => Task.FromResult(_byId.GetValueOrDefault(id));

    public Task AddRangeAsync(IEnumerable<LearningTask> tasks, CancellationToken ct = default)
    {
        foreach (var task in tasks)
        {
            _tasks.Add(task);
            _byId[task.Id] = task;
        }

        return Task.CompletedTask;
    }

    public Task UpdateAsync(LearningTask task, CancellationToken ct = default)
    {
        _byId[task.Id] = task;
        var index = _tasks.FindIndex(t => t.Id == task.Id);
        if (index >= 0)
        {
            _tasks[index] = task;
        }

        return Task.CompletedTask;
    }

    public IReadOnlyList<LearningTask> All => _tasks;

    public void Seed(LearningTask task)
    {
        _tasks.Add(task);
        _byId[task.Id] = task;
    }
}

public sealed class InMemoryActivityRepository : IActivityRepository
{
    private readonly SortedDictionary<DateOnly, LearningActivity> _byDate = [];

    public Task<LearningActivity?> GetAsync(DateOnly date, CancellationToken ct = default)
        => Task.FromResult(_byDate.GetValueOrDefault(date));

    public Task<IReadOnlyList<LearningActivity>> ListAsync(DateOnly from, DateOnly to, CancellationToken ct = default)
        => Task.FromResult<IReadOnlyList<LearningActivity>>(
            _byDate.Where(kv => kv.Key >= from && kv.Key <= to).Select(kv => kv.Value).ToList());

    public Task SaveAsync(LearningActivity activity, CancellationToken ct = default)
    {
        _byDate[activity.Date] = activity;
        return Task.CompletedTask;
    }

    public IReadOnlyList<LearningActivity> All => _byDate.Values.ToList();

    public void Seed(LearningActivity activity) => _byDate[activity.Date] = activity;

    /// <summary>Test helper: seed a day's activity without going through the service under test.</summary>
    public void SeedDay(DateOnly date, int completedLessons, long watchedMs, bool countsForStreak = true)
        => _byDate[date] = new LearningActivity
        {
            Date = date,
            CompletedLessons = completedLessons,
            WatchedMs = watchedMs,
            CountsForStreak = countsForStreak,
        };
}

public sealed class InMemoryCategoryRepository : ICategoryRepository
{
    private readonly List<Category> _categories = [];

    /// <summary>
    /// A category with no id yet would not exist in the real store: the SQLite repository assigns
    /// a key on insert, so a row still carrying the domain's <see cref="Guid"/> default cannot be
    /// read back out of it. This fake assigns one on the way out for the same reason — an id of
    /// <see cref="Guid.Empty"/> is not an inert placeholder, it is a well-formed <see cref="Guid"/>
    /// that any lookup reaching this repository through a widened parameter will happily match.
    ///
    /// <para>
    /// That is not hypothetical. A Core service resolving a course id through a widened parameter
    /// found this row first and answered a course-scoped question with it, and the course's own
    /// "Continue" task disappeared from its day. Assigning the id keeps the fake honest about
    /// what the store is allowed to contain.
    /// </para>
    /// </summary>
    public Task<IReadOnlyList<Category>> ListAsync(CancellationToken ct = default)
        => Task.FromResult<IReadOnlyList<Category>>(
            _categories.Select(Identified).OrderBy(category => category.Order).ToList());

    public Task<Category?> GetByNameAsync(string name, CancellationToken ct = default)
        => Task.FromResult(_categories.Select(Identified).FirstOrDefault(category => category.Name == name));

    public Task AddAsync(Category category, CancellationToken ct = default)
    {
        _categories.Add(Identified(category));
        return Task.CompletedTask;
    }

    public IReadOnlyList<Category> All => _categories;

    /// <summary>
    /// Gives an unset row the id it would have been given on insert, in place, so that a caller
    /// reading it twice sees the same id both times.
    /// </summary>
    private static Category Identified(Category category)
    {
        if (category.Id == Guid.Empty)
        {
            category.Id = Guid.NewGuid();
        }

        return category;
    }
}

public sealed class InMemoryLibrarySourceRepository : ILibrarySourceRepository
{
    private readonly List<LibrarySource> _sources = [];

    /// <summary>
    /// A source with no id is assigned one, for the reason given on
    /// <see cref="InMemoryCategoryRepository"/>. The stakes are higher here: a source still at
    /// <see cref="Guid.Empty"/> makes <see cref="GetAsync"/> answer "yes, I have a source with
    /// that id" for <see cref="Guid.Empty"/>, which is the id an unset Guid carries.
    /// </summary>
    public Task<LibrarySource?> GetAsync(Guid id, CancellationToken ct = default)
    {
        if (id == Guid.Empty)
        {
            return Task.FromResult<LibrarySource?>(null);
        }

        return Task.FromResult(_sources.FirstOrDefault(s => s.Id == id));
    }

    public Task<IReadOnlyList<LibrarySource>> ListAsync(CancellationToken ct = default)
        => Task.FromResult<IReadOnlyList<LibrarySource>>(_sources.Select(Identified).ToList());

    public Task AddAsync(LibrarySource source, CancellationToken ct = default)
    {
        _sources.Add(Identified(source));
        return Task.CompletedTask;
    }

    private static LibrarySource Identified(LibrarySource source)
    {
        if (source.Id == Guid.Empty)
        {
            source.Id = Guid.NewGuid();
        }

        return source;
    }
}

/// <summary>Counts commits, so a test can prove that a write went through the unit of work.</summary>
public sealed class CountingUnitOfWork : IUnitOfWork
{
    public int SaveCount { get; private set; }

    public Task SaveChangesAsync(CancellationToken ct = default)
    {
        SaveCount++;
        return Task.CompletedTask;
    }
}
